[package]
name = "sub-storage"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
jsonrpsee = { version = "0.1.0", features = ["ws"] }

sp-core = { path = "../../substrate/primitives/core" }
sp-runtime = { path = "../../substrate/primitives/runtime" }
frame-support = { path = "../../substrate/frame/support" }
sp-version = { path = "../../substrate/primitives/version" }
frame-metadata = { path = "../../substrate/frame/metadata" }

# Optional for helpers only.
frame-system = { path = "../../substrate/frame/system", optional = true }
pallet-identity = { path = "../../substrate/frame/identity", optional = true }
pallet-balances = { path = "../../substrate/frame/balances", optional = true }
ansi_term = { version = "0.12.1", optional = true }

[dev-dependencies]
async-std = { version = "1.7.0" }
hex-literal = "0.3.1"
hex = "0.4.2"
frame-system = { path = "../../substrate/frame/system" }
pallet-balances = { path = "../../substrate/frame/balances" }
pallet-staking = { path = "../../substrate/frame/staking" }
pallet-proxy = { path = "../../substrate/frame/proxy" }

[features]
remote-test-kusama = []
remote-test-polkadot = []
build-docs = []
default = []
helpers = [
	"frame-system",
	"pallet-identity",
	"pallet-balances",
	"ansi_term",
]
